### ISSUE TITLE
Hompage down / 502 Bad Gateway

### ISSUE THREAD

**Issue by laf0rge** [w84death/floppinux#7]
Seems like some reverse proxy trouble?

https://bits.p1x.in/floppinux/ shows 502 Bad Gateway

**Comment by superjamie** [comment]
Resolved with links to Internet Archive: https://github.com/w84death/floppinux/commit/d06c6765face2a4690628ed4dbe86064b0b180d0

**Comment by w84death** [comment]
I restored the old pages at https://krzysztofjankowski.com/floppinux/ and I'm working on restoring the whole blog.
